#!/bin/sh
if [ $1 == "update" ]; then
while true
do
  curl -s 'http://api.openweathermap.org/data/2.5/weather?q=Santiago,cl&units=metric' | python -c 'import json,sys;obj=json.load(sys.stdin);w=obj["weather"][0]["icon"];print("icon:"+w[:-1])' > ~/weather/weatherstatus
  curl -s 'http://api.openweathermap.org/data/2.5/weather?q=Santiago,cl&units=metric' | python -c 'import json,sys;obj=json.load(sys.stdin);print("forecast:"+obj["weather"][0]["description"])' >> ~/weather/weatherstatus
  curl -s 'http://api.openweathermap.org/data/2.5/weather?q=Santiago,cl&units=metric' | python -c 'import json,sys;obj=json.load(sys.stdin);print("temp:"+str(obj["main"]["temp"]))' >> ~/weather/weatherstatus 
  curl -s 'http://api.openweathermap.org/data/2.5/weather?q=Santiago,cl&units=metric' | python -c 'import json,sys;obj=json.load(sys.stdin);print("humidity:"+str(obj["main"]["humidity"]))' >> ~/weather/weatherstatus 
  curl -s 'http://api.openweathermap.org/data/2.5/weather?q=Santiago,cl&units=metric' | python -c 'import json,sys;obj=json.load(sys.stdin);print("windspeed:"+str(obj["wind"]["speed"]))' >> ~/weather/weatherstatus 
  sleep 3600
done
elif [ $1 == "icon" ]; then
  number=$(cat ~/weather/weatherstatus | grep $1 | cut -d ":" -f2)
  case $number in
    01) echo "A"
    ;;
    02) echo "b"
    ;;
    03) echo "d"
    ;;
    04) echo "e"
    ;;
    09) echo "h"
    ;;
    10) echo "g"
    ;;
    11) echo "i"
    ;;
    13) echo "k"
    ;;
  esac
    
else
  cat ~/weather/weatherstatus | grep $1 | cut -d ":" -f2
fi
