#! /bin/sh

sxhkd &
compton &

bspc monitor -d I II III IV V VI

bspc config border_width         5
bspc config window_gap          12
#bspc config border_radius       10

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#f92672"

bspc config top padding
feh --bg-fill ~/.local/share/spotlight/background.jpg
 ~/.config/lemonbar/panel &
