#! /bin/sh

sxhkd &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12
bspc config border_radius       10

bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-fill ~/Downloads/jackvanzet.jpg
~/.config/lemonbar/panel
